name: converse
description: "A simple chat app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  socket_io_client: ^2.0.3+1
  dio: ^5.4.3+1
  get_it: ^7.7.0
  dartz: ^0.10.1
  firebase_core: ^2.31.0
  firebase_auth_rest: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pngs/app-icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  background_image: assets/pngs/background.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/pngs/
    - assets/svgs/
