name: calculator_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  chiclet: ^1.2.0
  math_expressions: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  bloc_test: ^9.1.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/icons/app-icon.png"
  image_path_ios: "assets/icons/app-icon.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/icons/app-icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: League Spartan
      fonts:
        - asset: assets/font/LeagueSpartan-Black.ttf
        - asset: assets/font/LeagueSpartan-Bold.ttf
        - asset: assets/font/LeagueSpartan-ExtraBold.ttf
        - asset: assets/font/LeagueSpartan-ExtraLight.ttf
        - asset: assets/font/LeagueSpartan-Light.ttf
        - asset: assets/font/LeagueSpartan-Medium.ttf
        - asset: assets/font/LeagueSpartan-Regular.ttf
        - asset: assets/font/LeagueSpartan-SemiBold.ttf
        - asset: assets/font/LeagueSpartan-Thin.ttf
